"""p0_4 cms content tables (articles/pages/media/versions)

Revision ID: 10958fde8752
Revises: 8d20fb4d4148
Create Date: 2026-08-16 16:14:10.706537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = '10958fde8752'
down_revision: Union[str, Sequence[str], None] = '8d20fb4d4148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_articles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('canonical', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('featured_image', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_articles_slug'), 'cms_articles', ['slug'], unique=True)
    op.create_index(op.f('ix_cms_articles_title'), 'cms_articles', ['title'], unique=False)
    op.create_table('cms_media',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('r2_key', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('alt', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_pages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_pages_key'), 'cms_pages', ['key'], unique=True)
    op.create_table('cms_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_versions_object_id'), 'cms_versions', ['object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_versions_object_id'), table_name='cms_versions')
    op.drop_table('cms_versions')
    op.drop_index(op.f('ix_cms_pages_key'), table_name='cms_pages')
    op.drop_table('cms_pages')
    op.drop_table('cms_media')
    op.drop_index(op.f('ix_cms_articles_title'), table_name='cms_articles')
    op.drop_index(op.f('ix_cms_articles_slug'), table_name='cms_articles')
    op.drop_table('cms_articles')
    # ### end Alembic commands ###
