"""P7: subscriptions.last_credit_grant_at

Revision ID: 57a8681f0484
Revises: a7c0c5d2e9f4
Create Date: 2026-08-15 21:47:15.407188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = '57a8681f0484'
down_revision: Union[str, Sequence[str], None] = 'a7c0c5d2e9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_credit_grant_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_credit_grant_at')
    # ### end Alembic commands ###
