"""G8: notification_prefs

Revision ID: 5897f4417ccf
Revises: ea82d92314de
Create Date: 2026-08-16 00:07:13.668353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = '5897f4417ccf'
down_revision: Union[str, Sequence[str], None] = 'ea82d92314de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_prefs',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_insight', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('weekly_reflection', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('report_ready', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('quiet_start', sa.Integer(), nullable=False),
    sa.Column('quiet_end', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_prefs')
    # ### end Alembic commands ###
