"""P5: users.free_exploration_used

Revision ID: 7475dfc2998b
Revises: c0833e69209e
Create Date: 2026-08-15 21:13:49.585474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = '7475dfc2998b'
down_revision: Union[str, Sequence[str], None] = 'c0833e69209e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_exploration_used', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_exploration_used')
    # ### end Alembic commands ###
