"""d2 report_chunks pgvector

Revision ID: be499a77ca2b
Revises: 64397ea3dbf5
Create Date: 2026-08-14 11:06:58.894849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = 'be499a77ca2b'
down_revision: Union[str, Sequence[str], None] = '64397ea3dbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_chunks_report_id'), 'report_chunks', ['report_id'], unique=False)
    # HNSW index for cosine similarity search (D2)
    op.execute("CREATE INDEX IF NOT EXISTS ix_report_chunks_embedding_hnsw "
               "ON report_chunks USING hnsw (embedding vector_cosine_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_report_chunks_embedding_hnsw")
    op.drop_index(op.f('ix_report_chunks_report_id'), table_name='report_chunks')
    op.drop_table('report_chunks')
    # ### end Alembic commands ###
