"""P4: daily_reflections + streak

Revision ID: c0833e69209e
Revises: 9f2c41e8b0d1
Create Date: 2026-08-15 20:57:30.115021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = 'c0833e69209e'
down_revision: Union[str, Sequence[str], None] = '9f2c41e8b0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reflections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_local', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tz_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chart_id', 'day_local', name='uq_daily_reflection_chart_day')
    )
    op.create_index(op.f('ix_daily_reflections_chart_id'), 'daily_reflections', ['chart_id'], unique=False)
    op.create_index(op.f('ix_daily_reflections_day_local'), 'daily_reflections', ['day_local'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_reflections_day_local'), table_name='daily_reflections')
    op.drop_index(op.f('ix_daily_reflections_chart_id'), table_name='daily_reflections')
    op.drop_table('daily_reflections')
    # ### end Alembic commands ###
