"""b6: subscriptions.order_id + orders.error (refund lifecycle)

Revision ID: d4db5d787f91
Revises: 3c92dac1a241
Create Date: 2026-08-14 09:23:53.152309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = 'd4db5d787f91'
down_revision: Union[str, Sequence[str], None] = '3c92dac1a241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subscriptions', sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_subscriptions_order_id'), 'subscriptions', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_order_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'order_id')
    op.drop_column('orders', 'error')
    # ### end Alembic commands ###
