"""align schema to models (audit r3)

Revision ID: d4f2580df4bf
Revises: c4f1a2b3e5d7
Create Date: 2026-08-14 00:45:42.946806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = 'd4f2580df4bf'
down_revision: Union[str, Sequence[str], None] = 'c4f1a2b3e5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'chart_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'chart_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
