"""baseline schema

Revision ID: dfb85378c2bf
Revises: 
Create Date: 2026-08-13 17:27:43.063138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type used below

# revision identifiers, used by Alembic.
revision: str = 'dfb85378c2bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_chat_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'chat_id', name='uq_botstate_platform_chat')
    )
    op.create_index(op.f('ix_bot_chat_states_chat_id'), 'bot_chat_states', ['chat_id'], unique=False)
    op.create_index(op.f('ix_bot_chat_states_platform'), 'bot_chat_states', ['platform'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('llm_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gateway', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_runs_report_id'), 'llm_runs', ['report_id'], unique=False)
    op.create_table('plans',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_fa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle_fa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_toman', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_key'), 'prompt_versions', ['prompt_key'], unique=False)
    op.create_table('referral_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referrer_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_rial', sa.Integer(), nullable=False),
    sa.Column('reward_rial', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_events_code'), 'referral_events', ['code'], unique=False)
    op.create_index(op.f('ix_referral_events_order_id'), 'referral_events', ['order_id'], unique=False)
    op.create_table('secrets',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('subscriptions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_chart_id'), 'subscriptions', ['chart_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_chat_id'), 'subscriptions', ['chat_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('weekly_reflections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('week_start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reflections_chart_id'), 'weekly_reflections', ['chart_id'], unique=False)
    op.create_index(op.f('ix_weekly_reflections_week_start'), 'weekly_reflections', ['week_start'], unique=False)
    op.create_table('birth_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calendar_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_year', sa.Integer(), nullable=False),
    sa.Column('raw_month', sa.Integer(), nullable=False),
    sa.Column('raw_day', sa.Integer(), nullable=False),
    sa.Column('time_known', sa.Boolean(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('city_fa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('province_fa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('tz_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('utc_datetime', sa.DateTime(), nullable=True),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personal_question', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_birth_profiles_user_id'), 'birth_profiles', ['user_id'], unique=False)
    op.create_table('referral_codes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_codes_code'), 'referral_codes', ['code'], unique=True)
    op.create_index(op.f('ix_referral_codes_user_id'), 'referral_codes', ['user_id'], unique=False)
    op.create_table('charts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chart_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engine_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('svg_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['birth_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charts_access_token'), 'charts', ['access_token'], unique=False)
    op.create_index(op.f('ix_charts_profile_id'), 'charts', ['profile_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_rial', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coupon_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('card_pan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_chart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['plan_key'], ['plans.key'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['birth_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_authority'), 'orders', ['authority'], unique=False)
    op.create_index(op.f('ix_orders_chart_id'), 'orders', ['chart_id'], unique=False)
    op.create_index(op.f('ix_orders_chat_id'), 'orders', ['chat_id'], unique=False)
    op.create_index(op.f('ix_orders_plan_key'), 'orders', ['plan_key'], unique=False)
    op.create_index(op.f('ix_orders_profile_id'), 'orders', ['profile_id'], unique=False)
    op.create_index(op.f('ix_orders_report_id'), 'orders', ['report_id'], unique=False)
    op.create_index(op.f('ix_orders_secondary_chart_id'), 'orders', ['secondary_chart_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('r2_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_chart_id'), 'reports', ['chart_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_chart_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_orders_secondary_chart_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_report_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_profile_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_plan_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_chat_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_chart_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_authority'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_charts_profile_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_access_token'), table_name='charts')
    op.drop_table('charts')
    op.drop_index(op.f('ix_referral_codes_user_id'), table_name='referral_codes')
    op.drop_index(op.f('ix_referral_codes_code'), table_name='referral_codes')
    op.drop_table('referral_codes')
    op.drop_index(op.f('ix_birth_profiles_user_id'), table_name='birth_profiles')
    op.drop_table('birth_profiles')
    op.drop_index(op.f('ix_weekly_reflections_week_start'), table_name='weekly_reflections')
    op.drop_index(op.f('ix_weekly_reflections_chart_id'), table_name='weekly_reflections')
    op.drop_table('weekly_reflections')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_chat_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_chart_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_referral_events_order_id'), table_name='referral_events')
    op.drop_index(op.f('ix_referral_events_code'), table_name='referral_events')
    op.drop_table('referral_events')
    op.drop_index(op.f('ix_prompt_versions_prompt_key'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_table('plans')
    op.drop_index(op.f('ix_llm_runs_report_id'), table_name='llm_runs')
    op.drop_table('llm_runs')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_bot_chat_states_platform'), table_name='bot_chat_states')
    op.drop_index(op.f('ix_bot_chat_states_chat_id'), table_name='bot_chat_states')
    op.drop_table('bot_chat_states')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
