"""P8: coupons.report_only

Revision ID: ea82d92314de
Revises: 57a8681f0484
Create Date: 2026-08-15 22:07:43.626132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = 'ea82d92314de'
down_revision: Union[str, Sequence[str], None] = '57a8681f0484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('report_only', sa.Boolean(),
                                       nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'report_only')
    # ### end Alembic commands ###
