"""P3: users.credits + explorations + credit_transactions

Revision ID: fd5cf11364ab
Revises: 435333592075
Create Date: 2026-08-15 20:29:21.109109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes  # noqa: F401 — SQLModel AutoString type

# revision identifiers, used by Alembic.
revision: str = 'fd5cf11364ab'
down_revision: Union[str, Sequence[str], None] = '435333592075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('explorations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_fa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credits_cost', sa.Integer(), nullable=False),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explorations_chart_id'), 'explorations', ['chart_id'], unique=False)
    op.create_index(op.f('ix_explorations_user_id'), 'explorations', ['user_id'], unique=False)
    op.add_column('users', sa.Column('credits', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits')
    op.drop_index(op.f('ix_explorations_user_id'), table_name='explorations')
    op.drop_index(op.f('ix_explorations_chart_id'), table_name='explorations')
    op.drop_table('explorations')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
