"""Route inventory for chart-platform (HERMES-PLAN-v1 · E1).

Iterates FastAPI's app.routes and produces docs/qa/ROUTE-INVENTORY.md,
flagging every route that no test references (test debt).

Usage:
    APP_ENV=dev venv/bin/python scripts/route_inventory.py
"""
from __future__ import annotations

import inspect
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from fastapi.routing import APIRoute  # noqa: E402


def _inspect_route(endpoint) -> tuple[str, str]:
    """Return (template_file, source) best-effort from an endpoint."""
    src = ""
    try:
        src = inspect.getsource(endpoint)
    except (TypeError, OSError):
        pass
    # TemplateResponse(name="<file>.html") or templates.TemplateResponse(...)
    m = re.search(r'"([A-Za-z0-9_\-/\.]+\.html)"', src)
    template = m.group(1) if m else ""
    return template, src


def classify(path: str, endpoint) -> tuple[str, str, str]:
    """Return (kind, template, source)."""
    template, src = _inspect_route(endpoint)
    is_api = path.startswith("/api/")
    is_page = (not is_api) and (template or "TemplateResponse" in src)
    kind = "page" if is_page else ("api" if is_api else "page")
    return kind, template, src


def test_covers(path: str, endpoint) -> bool:
    """True if any test references this route path or endpoint function name."""
    tests_root = ROOT / "tests"
    hay = " ".join(
        p.read_text(encoding="utf-8", errors="ignore")
        for p in tests_root.glob("*.py")
    )
    if path in hay:
        return True
    name = getattr(endpoint, "__name__", "")
    if name and re.search(rf"\b{re.escape(name)}\b", hay):
        return True
    return False


def main() -> int:
    from app.main import app

    rows = []
    for r in app.routes:
        if not isinstance(r, APIRoute):
            continue
        path = r.path
        methods = ",".join(sorted(m for m in r.methods if m not in ("HEAD", "OPTIONS")))
        kind, template, _src = classify(path, r.endpoint)
        covered = test_covers(path, r.endpoint)
        auth = "h" if any(k in path for k in ("/account", "/profile", "/me", "/admin")) else "-"
        credit = "h" if ("/explore" in path or "/credits" in path) else "-"
        rows.append((path, methods, kind, covered, auth, credit, template))

    rows.sort(key=lambda r: (r[2] != "page", r[0], r[1]))
    total = len(rows)
    uncovered = [r for r in rows if not r[3]]

    out = [
        "# Route Inventory — chart-platform",
        "",
        f"> Generated by `scripts/route_inventory.py` on **{date.today()}**. "
        f"Total routes: **{total}**. Routes with **no test reference**: "
        f"**{len(uncovered)}** (test debt).",
        "",
        "> `احراز` / `اعتبار` ستونها **heuristic** (از مسیر حدس زده شدهاند)، نه حقیقتِ گیت؛ "
        "برای حقیقت bodyِ اندپوینت را بخوان. ستون کلیدیِ عملی **تست؟** است: ",
        "> هر مسیری که `⚠️` داشته باشد = بدهی تست (باید در E3 تست بگیرد).",
        "",
        "| مسیر | متد | نوع | احراز | اعتبار | قالب | تست؟ |",
        "|---|---|---|---|---|---|---|",
    ]
    for path, methods, kind, covered, auth, credit, template in rows:
        out.append(
            f"| `{path}` | {methods} | {kind} | {auth} | {credit} "
            f"| {template or '-'} | {'✅' if covered else '⚠️'} |"
        )

    out += ["", "---", "", "## بدهی تست (مسیرهای بدون تست)", ""]
    if uncovered:
        for path, methods, kind, _, _, _, _ in uncovered:
            out.append(f"- `{path}` ({methods}) — {kind}")
    else:
        out.append("- هیچ — همهٔ مسیرها حداقل یک ارجاع تست دارند.")

    dest = ROOT / "docs" / "qa" / "ROUTE-INVENTORY.md"
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Inventory written: {dest}")
    print(f"  total routes: {total}")
    print(f"  no-test routes: {len(uncovered)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
